---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2
    run_list:
      - recipe[apt] # update package index
  - name: ubuntu-14.04
    run_list:
      - recipe[apt] # update package index
    run_list:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[tmux]
      - recipe[git]
      - recipe[vim]
      - recipe[dotfiles]
    attributes:
      tmux:
        version: 2.1
        checksum: 31564e7bf4bcef2defb3cb34b9e596bd43a3937cad9e5438701a81a5a9af6176
        install_method: source
        session_opts:
          prefix: C-b
