---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[user::data_bag]
    data_bags_path: test/integration/data_bags
    attributes:
      users:
        - brock
        - misty

suites:
  - name: default
    run_list:
      - recipe[dotfiles]
    verifier:
      inspec_tests:
        - test/smoke/default
