name 'dotfiles'
maintainer 'The Authors'
maintainer_email 'andersonbravalheri@gmail.com'
license 'all_rights'
description 'Installs/Configures dotfiles'
long_description 'Installs/Configures dotfiles'
version '0.1.0'
