" Vim reads .vim/vimrc when .vimrc does not exist

" Effort to make vim more XDG-basedir compatible
" obs.: vim will not create these directories
set undodir=$CACHE_HOME/vim/undo,~/,/tmp
set directory=$CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$CACHE_HOME/vim/backup,~/,/tmp
set viminfo+=n$CACHE_HOME/vim/viminfo

" Layout decisions:
" - configration files placed under ~/.config/vim
" - plugins, libraries and runtim dependencies placed under $VIMDIR (~/.vim)

" Bootstrap vim configurations
source $CONFIG_HOME/vim/main.vim